sites:
  artnews-com:
    skip_provisioning: true
    description: artnews.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - artnews-com.test
    custom:
      live_url: https://artnews.com
      site_title: Artnews (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-artnews-2019.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  bgr-com:
    skip_provisioning: true
    description: bgr.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - bgr-com.test
    custom:
      live_url: https://bgr.com
      site_title: BGR (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/bgr.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  billboard-com:
    skip_provisioning: true
    description: billboard.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - billboard-com.test
    custom:
      live_url: https://billboard.com
      site_title: Billboard (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-billboard-2021.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  blogher-com:
    skip_provisioning: true
    description: blogher.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - blogher-com.test
    custom:
      live_url: https://blogher.com
      site_title: BlogHer (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-blogher-2020.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  deadline-com:
    skip_provisioning: true
    description: deadline.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - deadline-com.test
    custom:
      live_url: https://deadline.com
      site_title: Deadline (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-deadline-2019.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  dirt-com:
    skip_provisioning: true
    description: dirt.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - dirt-com.test
    custom:
      live_url: https://dirt.com
      site_title: Dirt (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-dirt-2020.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  events-fairchildlive-com:
    skip_provisioning: true
    description: events.fairchildlive.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - events-fairchildlive-com.test
    custom:
      live_url: https://events.fairchildlive.com
      site_title: Fairchild Live Events (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-summits-wwd.git
        theme_slug: ""
        parent_theme_slug: pmc-summits
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  footwearnews-com:
    skip_provisioning: true
    description: footwearnews.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - footwearnews-com.test
    custom:
      live_url: https://footwearnews.com
      site_title: Footwearnews (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-footwearnews-2018.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  goldderby-com:
    skip_provisioning: true
    description: goldderby.com
    repo: git@github.com:Varying-Vagrant-Vagrants/custom-site-template.git
    branch: master
    hosts:
      - goldderby-com.test
    custom:
      live_url: https://goldderby.com
      site_title: Gold Derby (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-goldderby.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  hollywoodlife-com:
    skip_provisioning: true
    description: hollywoodlife.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - hollywoodlife-com.test
    custom:
      live_url: https://hollywoodlife.com
      site_title: Hollywoodlife (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-hollywoodlife-2017.git
        theme_slug: ""
        parent_theme_slug: pmc-core-2017
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  hollywoodreporter-com:
    skip_provisioning: true
    description: hollywoodreporter.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - hollywoodreporter-com.test
    custom:
      live_url: https://hollywoodreporter.com
      site_title: Hollywoodreporter (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-hollywoodreporter-2021.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  indiewire-com:
    skip_provisioning: true
    description: indiewire.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - indiewire-com.test
    custom:
      live_url: https://indiewire.com
      site_title: Indiewire (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-indiewire-2016.git
        theme_slug: indiewire
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  pmc-com:
    skip_provisioning: true
    description: pmc.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - pmc-com.test
    custom:
      live_url: https://pmc.com
      site_title: PMC Corp (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-corporate-2018.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  robbreport-com:
    skip_provisioning: true
    description: robbreport.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - robbreport-com.test
    custom:
      live_url: https://robbreport.com
      site_title: Robb Report (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-robbreport-2017-v2.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  rollingstone-com:
    skip_provisioning: true
    description: rollingstone.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - rollingstone-com.test
    custom:
      live_url: https://rollingstone.com
      site_title: Rolling Stone (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-rollingstone-2018.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  rr1-com:
    skip_provisioning: true
    description: rr1.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - rr1-com.test
    custom:
      live_url: https://rr1.com
      site_title: RR1 (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-summits-rr1.git
        theme_slug: ""
        parent_theme_slug: pmc-summits
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  sales-pmcdev-io:
    skip_provisioning: true
    description: sales.pmcdev.io
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - sales-pmcdev-io.test
    custom:
      live_url: https://sales.pmcdev.io
      site_title: Sales Microsites (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-salesmicrosite.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  sheknows-com:
    skip_provisioning: true
    description: sheknows.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - sheknows-com.test
    custom:
      live_url: https://sheknows.com
      site_title: Sheknows (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-sheknows-2020.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  soaps-com:
    skip_provisioning: true
    description: soaps.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - soaps-com.test
    custom:
      live_url: https://soaps.com
      site_title: Soaps (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-soaps-2018.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  sportico-com:
    skip_provisioning: true
    description: sportico.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - sportico-com.test
    custom:
      live_url: https://sportico.com
      site_title: Sportico (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-sportico-2020.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  sourcingjournal-com:
    skip_provisioning: true
    description: sourcingjournal.com
    repo: git@github.com:Varying-Vagrant-Vagrants/custom-site-template.git
    branch: master
    hosts:
      - sourcingjournal-com.test
    custom:
      live_url: https://sourcingjournal.com
      site_title: Sourcing Journal (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-sourcingjournal-2018.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  sourcingjournal-2021-com:
    skip_provisioning: true
    description: sourcingjournal-2021.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - sourcingjournal-2021-com.test
    custom:
      live_url: https://sourcingjournal-2021.com
      site_title: Sourcing Journal (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-sourcingjournal-2021.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  spy-com:
    skip_provisioning: true
    description: spy.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - spy-com.test
    custom:
      live_url: https://spy.com
      site_title: Spy (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-spy.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  stylecaster-com:
    skip_provisioning: true
    description: stylecaster.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - stylecaster-com.test
    custom:
      live_url: https://stylecaster.com
      site_title: Stylecaster (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@github.com:penske-media-corp/sc-stylecaster-2016.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  tvline-com:
    skip_provisioning: true
    description: tvline.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - tvline-com.test
    custom:
      live_url: https://tvline.com
      site_title: TV Line (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-tvline-2014.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  variety-com:
    skip_provisioning: true
    description: variety.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - variety-com.test
    custom:
      live_url: https://variety.com
      site_title: Variety (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-variety-2020.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  vibe-com:
    skip_provisioning: true
    description: vibe.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - vibe-com.test
    custom:
      live_url: https://vibe.com
      site_title: Vibe (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-vibe-2021.git
        theme_slug: ""
        parent_theme_slug: pmc-core-v2
        grandchild_theme_repo: ""
        theme_dir_uses_vip: true
  wwd-com:
    skip_provisioning: true
    description: wwd.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - wwd-com.test
    custom:
      live_url: https://wwd.com
      site_title: WWD (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-wwd-2016.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  wwd-2021-com:
    skip_provisioning: true
    description: wwd-2021.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - wwd-2021-com.test
    custom:
      live_url: https://wwd-2021.com
      site_title: WWD 2021 (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-wwd-2021.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  studios-wwd-com:
    skip_provisioning: true
    description: studios.wwd.com
    repo: git@github.com:penske-media-corp/pmc-vvv-site-provisioners.git
    branch: main
    hosts:
      - studios-wwd-com.test
    custom:
      live_url: https://studios.wwd.com
      site_title: WWD Studios (LOCAL)
      admin_user: pmcdev
      admin_password: pmcdev
      pmc:
        theme_repo: git@bitbucket.org:penskemediacorp/pmc-wwd-studios-2017.git
        theme_slug: ""
        parent_theme_slug: ""
        grandchild_theme_repo: ""
        theme_dir_uses_vip: false
  wordpress-trunk:
    skip_provisioning: true
    description: An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test
utilities:
  core:
    - tls-ca
    - phpmyadmin
    - memcached-admin
    - opcache-status
    - tideways
    - webgrind
    - mongodb
    - php73
    - php74
  pmc:
    - coretech
    - http-concat
    - phpcs
utility-sources:
  pmc:
    repo: git@github.com:penske-media-corp/pmc-vvv-utilities.git
    branch: main
vm_config:
  memory: 4096
  cores: 3
general:
  db_backup: true
  db_restore: true
  db_share: false
vagrant-plugins:
  disksize: 65GB
