---
sites:
  # wpcom:
    # skip_provisioning: false
    # repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    # hosts:
      # - bgr.wpcom.test
      # - pmc-corporate-2018.wpcom.test
      # - pmc-deadline-2019.wpcom.test
      # - pmc-footwearnews-2018.wpcom.test
      # - pmc-hollywoodlife-2017.wpcom.test
      # - pmc-robbreport-2017-v2.test
      # - pmc-sheknows-2018.wpcom.test
      # - pmc-spy.wpcom.test
      # - pmc-summits-rr1.wpcom.test
      # - pmc-summits-variety.wpcom.test
      # - pmc-summits-wwd.wpcom.test
      # - pmc-summits.wpcom.test
      # - pmc-tvline.wpcom.test
      # - pmc-variety-2017.wpcom.test
      # - pmc-wwd-2016.wpcom.test
      # - wpcom.test
    # custom:
      # wp_type: subdomain

# VIPGO sites:
# @NOTE: name === theme-name && host
#
  # @TODO: what is this site?
  # @TODO: how to explain use?
  # https://github.com/wpcomvip/pmc
  # https://bitbucket.com/penskemediacorp/pmc-corporate-2018
  # pmc-vipgo-staging:
    # skip_provisioning: false
    # description: "pmc"
    # repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    # custom:
      # delete_default_plugins: true
      # install_test_content: true
      # wpconfig_constants:
        # AUTOMATIC_UPDATER_DISABLED: true
        # DISALLOW_FILE_EDIT: true
        # DISALLOW_FILE_MODS: true
        # WP_DEBUG: true
        # WP_DEBUG_LOG: true
        # WP_DISABLE_FATAL_ERROR_HANDLER: true
      # admin_user: admin
      # admin_password: password
      # admin_email: admin@pmc.test
      # live_url: https://pmc.com
    # hosts:
      # - pmc.test

  # https://github.com/wpcomvip/pmc-artnews
  # https://bitbucket.com/penskemediacorp/pmc-artnews-2019
  pmc-artnews-2019:
    skip_provisioning: false
    description: "pmc-artnews-2019"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_test_content: true
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISALLOW_FILE_EDIT: true
        DISALLOW_FILE_MODS: true
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
      admin_user: admin
      admin_password: password
      admin_email: admin@pmc.test
      live_url: https://artnews.com
    hosts:
      - pmc-artnews-2019.test

  # @TODO: how to provision?
  # https://github.com/wpcomvip/pmc-dirt
  # https://bitbucket.com/penskemediacorp/felt # <- @TODO: Theme will not work it needs to be prefixed with pmc-
  # dirt/felt
  # felt:
    # skip_provisioning: false
    # description: "felt/dirt"
    # repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    # custom:
      # delete_default_plugins: true
      # install_test_content: true
      # wpconfig_constants:
        # AUTOMATIC_UPDATER_DISABLED: true
        # DISALLOW_FILE_EDIT: true
        # DISALLOW_FILE_MODS: true
        # WP_DEBUG: true
        # WP_DEBUG_LOG: true
        # WP_DISABLE_FATAL_ERROR_HANDLER: true
      # admin_user: admin
      # admin_password: password
      # admin_email: admin@pmc.test
      # live_url: https://dirt.com
    # hosts:
      # - dirt.test

  # https://github.com/wpcomvip/pmc-goldderby
  # https://bitbucket.com/penskemediacorp/pmc-goldderby
  pmc-goldderby:
    skip_provisioning: false
    description: "pmc-goldderby"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_test_content: true
      #@TODO: May need to automate plugin activation before theme
      install_plugins:
        - bbpress
        - buddypress
        - buddypress-messages-spam-blocker
        - buddypress-vip-go
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISALLOW_FILE_EDIT: true
        DISALLOW_FILE_MODS: true
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
      admin_user: admin
      admin_password: password
      admin_email: admin@pmc.test
      live_url: https://goldderby.com
    hosts:
      - pmc-goldderby.test

  # https://github.com/wpcomvip/pmc-indiewire
  # https://bitbucket.com/penskemediacorp/pmc-indiewire-2016
  pmc-indiewire-2016:
    skip_provisioning: false
    description: "pmc-indiewire-2016"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_test_content: true
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISALLOW_FILE_EDIT: true
        DISALLOW_FILE_MODS: true
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
      admin_user: admin
      admin_password: password
      admin_email: admin@pmc.test
      live_url: https://indiewire.com
    hosts:
      - pmc-indiewire-2016.test

  # @TODO: what to do with this site?
  # https://github.com/wpcomvip/pmc-artnews
  # https://bitbucket.com/penskemediacorp/pmc-robbreport-uk
  # pmc-robbreport-uk:
    # skip_provisioning: false
    # description: "pmc-robbreport-uk"
    # repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    # custom:
      # delete_default_plugins: true
      # install_test_content: true
      # wpconfig_constants:
        # AUTOMATIC_UPDATER_DISABLED: true
        # DISALLOW_FILE_EDIT: true
        # DISALLOW_FILE_MODS: true
        # WP_DEBUG: true
        # WP_DEBUG_LOG: true
        # WP_DISABLE_FATAL_ERROR_HANDLER: true
      # admin_user: admin
      # admin_password: password
      # admin_email: admin@pmc.test
      # live_url: https://robbreport.co.uk
    # hosts:
      # - pmc-robbreport-uk.test

  # https://github.com/wpcomvip/pmc-rollingstone
  # https://bitbucket.com/penskemediacorp/pmc-rollingstone-2018
  pmc-rollingstone-2018:
    skip_provisioning: false
    description: "pmc-rollingstone"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_test_content: true
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISALLOW_FILE_EDIT: true
        DISALLOW_FILE_MODS: true
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
      admin_user: admin
      admin_password: password
      admin_email: admin@pmc.test
      live_url: https://rollingstone.com
    hosts:
      - pmc-rollingstone-2018.test

  # @TODO: what is this site?
  # https://github.com/wpcomvip/pmc-salesmicrosite
  # https://bitbucket.com/penskemediacorp/pmc-salesmicrosite
  # pmc-salesmicrosite:
  #   skip_provisioning: false
  #   description: "pmc-salesmicrosite"
  #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #   custom:
  #     delete_default_plugins: true
  #     install_test_content: true
  #     wpconfig_constants:
  #       AUTOMATIC_UPDATER_DISABLED: true
  #       DISALLOW_FILE_EDIT: true
  #       DISALLOW_FILE_MODS: true
  #       WP_DEBUG: true
  #       WP_DEBUG_LOG: true
  #       WP_DISABLE_FATAL_ERROR_HANDLER: true
  #     admin_user: admin
  #     admin_password: password
  #     admin_email: admin@pmc.test
  #     #@TODO: what's the live url? live_url: https://pmc.com
  #   hosts:
  #     - pmc-salesmicrosite.test

  # https://github.com/wpcomvip/pmc-sheknows
  # https://bitbucket.com/penskemediacorp/pmc-sheknows-2018
  pmc-sheknows-2018:
    skip_provisioning: false
    description: "pmc-sheknows-2018"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_test_content: true
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISALLOW_FILE_EDIT: true
        DISALLOW_FILE_MODS: true
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
      admin_user: admin
      admin_password: password
      admin_email: admin@pmc.test
      live_url: https://sheknows.com
    hosts:
      - pmc-sheknows-2018.test

  # @TODO: how to provision?
  # https://github.com/wpcomvip/pmc-sheknowsmedia
  # https://github.com/sheknows/sheknowsmedia.com
  # pmc-sheknowsmedia.com:
  #   skip_provisioning: false
  #   description: "pmc"
  #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #   custom:
  #     delete_default_plugins: true
  #     install_test_content: true
  #     wpconfig_constants:
  #       AUTOMATIC_UPDATER_DISABLED: true
  #       DISALLOW_FILE_EDIT: true
  #       DISALLOW_FILE_MODS: true
  #       WP_DEBUG: true
  #       WP_DEBUG_LOG: true
  #       WP_DISABLE_FATAL_ERROR_HANDLER: true
  #     admin_user: admin
  #     admin_password: password
  #     admin_email: admin@pmc.test
  #     live_url: https://sheknowsmedia.com
  #   hosts:
  #     - sheknowsmedia.com.test

  # https://github.com/wpcomvip/pmc-soaps
  # https://bitbucket.com/penskemediacorp/pmc-soaps-2018
  pmc-soaps-2018:
    skip_provisioning: false
    description: "pmc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_test_content: true
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISALLOW_FILE_EDIT: true
        DISALLOW_FILE_MODS: true
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
      admin_user: admin
      admin_password: password
      admin_email: admin@pmc.test
      live_url: https://soaps.com
    hosts:
      - pmc-soaps-2018.test

  # @TODO: how to provision?
  # https://github.com/wpcomvip/pmc-stylecaster-com
  # https://github.com/sheknows/sc-stylecaster-2016
  # sc-stylecaster-2016:
  #   skip_provisioning: false
  #   description: "sc-stylecaster-2016"
  #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #   custom:
  #     delete_default_plugins: true
  #     install_test_content: true
  #     wpconfig_constants:
  #       AUTOMATIC_UPDATER_DISABLED: true
  #       DISALLOW_FILE_EDIT: true
  #       DISALLOW_FILE_MODS: true
  #       WP_DEBUG: true
  #       WP_DEBUG_LOG: true
  #       WP_DISABLE_FATAL_ERROR_HANDLER: true
  #     admin_user: admin
  #     admin_password: password
  #     admin_email: admin@pmc.test
  #     live_url: https://stylecaster.com
  #   hosts:
  #     - sc-stylecaster-2016.test

  # @TODO: what is this site?
  # https://github.com/wpcomvip/pmc
  # https://bitbucket.com/penskemediacorp/pmc-corporate-2018
  # pmc-variety-com:
  #   skip_provisioning: false
  #   description: "pmc-variety-com"
  #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #   custom:
  #     delete_default_plugins: true
  #     install_test_content: true
  #     wpconfig_constants:
  #       AUTOMATIC_UPDATER_DISABLED: true
  #       DISALLOW_FILE_EDIT: true
  #       DISALLOW_FILE_MODS: true
  #       WP_DEBUG: true
  #       WP_DEBUG_LOG: true
  #       WP_DISABLE_FATAL_ERROR_HANDLER: true
  #     admin_user: admin
  #     admin_password: password
  #     admin_email: admin@pmc.test
  #     live_url: https://pmc-variety-com.com
  #   hosts:
  #     - pmc-variety-com.test

  # #@TODO: what is this site?
  # https://github.com/wpcomvip/pmc-variety-com
  # https://bitbucket.com/penskemediacorp/pmc-variety-com
  # pmc-variety-com:
  #   skip_provisioning: false
  #   description: "pmc-variety-com"
  #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #   custom:
  #     delete_default_plugins: true
  #     install_test_content: true
  #     wpconfig_constants:
  #       AUTOMATIC_UPDATER_DISABLED: true
  #       DISALLOW_FILE_EDIT: true
  #       DISALLOW_FILE_MODS: true
  #       WP_DEBUG: true
  #       WP_DEBUG_LOG: true
  #       WP_DISABLE_FATAL_ERROR_HANDLER: true
  #     admin_user: admin
  #     admin_password: password
  #     admin_email: admin@pmc.test
  #     live_url: https://pmc-variety-com.com
  #   hosts:
  #     - pmc-variety-com.test

utilities:
  core:
    - memcached-admin
    - mongodb
    - opcache-status
    - php74
    - phpmyadmin
    - tideways
    - tls-ca
    - webgrind

vm_config:
  cores: 2
  memory: 2048

general:
  db_backup: true
  db_restore: true
  db_share_type: false

vagrant-plugins:
  disksize: 10GB
